baseURL: 'https://docs.lanyards.app/'
title: Lanyards
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: What is Lanyards?
      url: /what-is-lanyards/
      weight: 1
    - name: Why Lanyards?
      url: /why-lanyards/
      weight: 2
    - name: Contribute
      url: /contribute/
      weight: 3
    - name: Roadmap
      url: /roadmap/
      weight: 4
    - name: Contact
      url: /links/
      weight: 5

params:
  description: 'One link to make your research life easier to share! Papers, talks, affiliations, socials, whatever... Easy, free, decentralised. A dedicated profile for researchers, built on the AT Protocol.'
  author: Lanyards
  DateFormat: 'January 2006'
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: false
  ShowShareButtons: false
  ShowReadingTime: true
  disableSpecialistPost: false
  disableAnchoredHeadings: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: true
  MainSections: ['documentation']
  ShowToc: true
  disableScrollToTop: false
  TocOpen: false
  ShowWordCount: true
  UseHugoToc: true
  comments: true
  math: false
  profileMode:
    enabled: true
    title: Lanyards Documentation
    subtitle: 'One link to make your research life easier to share! Papers, talks, affiliations, socials, whatever... Easy, free, decentralised. A dedicated profile for researchers, built on the AT Protocol.'
    imageUrl: ''
    imageWidth: 160
    imageHeight: 160
    buttons:
      - name: What is Lanyards?
        url: /what-is-lanyards/
      - name: Why Lanyards?
        url: /why-lanyards/
      - name: Contribute
        url: /contribute/
      - name: Roadmap
        url: /roadmap/
      - name: Contact
        url: /links/

  socialIcons:
    - name: GitHub
      url: https://github.com/renderghost/lanyards
    - name: Bluesky
      url: https://bsky.app/profile/lanyards.app
    - name: Barry
      url: https://bsky.app/profile/renderg.host

  assets:
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: 'Lanyards'
    icon: favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
