# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/

baseURL: 'https://docs.lanyards.app/'
title: Lanyards
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: What is Lanyards?
      url: /what-is-lanyards/
      weight: 1
    - name: Why Lanyards?
      url: /why-lanyards/
      weight: 2
    - name: Contribute
      url: /contribute/
      weight: 3
    - name: Roadmap
      url: /roadmap/
      weight: 4
    - name: Contact
      url: /links/
      weight: 5

params:
  # defaultTheme: dark
  # defaultTheme: light
  author: '@renderg.host'
  comments: true
  DateFormat: 'January 2006'
  defaultTheme: auto
  description: 'One link to make your research life easier to share! Papers, talks, affiliations, socials, whatever... Easy, free, decentralised. A dedicated profile for researchers, built on the AT Protocol.'
  disableAnchoredHeadings: false
  disableScrollToTop: false
  disableSpecialistPost: false
  disableThemeToggle: false
  hideFooter: false
  MainSections: ['documentation']
  ShowAllPagesInArchive: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  ShowReadingTime: true
  ShowShareButtons: false
  ShowToc: false
  ShowWordCount: true
  TocOpen: false
  UseHugoToc: true
  math: false
  # homeInfoParams:
  #   Title: Hi there wave
  #   Content: Can be Info, links, about...
  profileMode:
    enabled: true
    title: Welcome to Lanyards
    subtitle: 'One link to make your research life easier to share! Papers, talks, affiliations, socials, whatever... Easy, free, decentralised. A dedicated profile for researchers, built on the AT Protocol.'
    imageUrl: '/apple-touch-icon.png'
    imageWidth: 90
    imageHeight: 90
    buttons:
      - name: What?
        url: /what-is-lanyards/
      - name: Why?
        url: /why-lanyards/
      - name: Contribute
        url: /contribute/
      - name: Roadmap
        url: /roadmap/
      - name: Contact
        url: /links/
  socialIcons:
    - name: GitHub
      url: https://github.com/renderghost/lanyards
    - name: Bluesky
      url: https://bsky.app/profile/lanyards.app
    - name: Barry
      url: https://bsky.app/profile/renderg.host

  assets:
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: 'Lanyards'
    icon: favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
